"""Generated by sandals."""

import collections.abc as cabc
from enum import Enum, auto
import sqlite3
import typing as t


STRUCTURED_VALUE_COL: t.Final[str] = "value"


type PodType = type[int | float | str]
type PodData = int | float | str
type StructuredData = list[PodData]
type CompoundData = list[DataClass]


class PodSqlite(t.NamedTuple):
    type_: PodType
    sql: str


SQLITE_POD_TYPE_MAP: t.Final[dict[str, PodSqlite]] = {
    "bool": PodSqlite(type_=bool, sql="INTEGER"),
    "int": PodSqlite(type_=int, sql="INTEGER"),
    "float": PodSqlite(type_=float, sql="REAL"),
    "str": PodSqlite(type_=str, sql="TEXT"),
}


class Kind(Enum):
    # Plain Ol' Data -- bool, int, float, str
    POD = 1
    # Data Class -- other custom data types
    DC = auto()
    # Lists of POD
    STRUCTURED = auto()
    # Lists of DC
    COMPOUND = auto()


class Field:
    def __init__(self, name: str, py_type: type, sql_type: str, kind: Kind) -> None:
        self.name: str = name
        self.py_type: type = py_type
        self.sql_type: str = sql_type
        self.kind: Kind = kind

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self.name!r}, {self.py_type.__name__}, {self.sql_type!r}, {self.kind.name})"


class DataClass:
    """Holds data going to and coming from SQLite databases."""

    table_name: str
    fields: list[Field]

    def __init_subclass__(cls) -> None:
        cls.fields_by_kind: dict[Kind, list[Field]] = cls.get_fields_by_kind()
        cls.fields_pod: list[Field] = cls.fields_by_kind[Kind.POD]
        cls.fields_structured: list[Field] = cls.fields_by_kind[Kind.STRUCTURED]
        cls.fields_dc: list[Field] = cls.fields_by_kind[Kind.DC]
        cls.fields_compound: list[Field] = cls.fields_by_kind[Kind.COMPOUND]

    @classmethod
    def get_fields_by_kind(cls) -> dict[Kind, list[Field]]:
        fbk: dict[Kind, list[Field]] = {
            Kind.POD: [],
            Kind.STRUCTURED: [],
            Kind.DC: [],
            Kind.COMPOUND: [],
        }
        for f in cls.fields:
            fbk[f.kind].append(f)
        return fbk

    @classmethod
    def from_dict_with_cast(cls, data: dict[str, t.Any]) -> "DataClass":
        cast: dict[str, t.Any] = {}

        for f in cls.fields:
            try:
                v: t.Any = data[f.name]
            except KeyError as e:
                raise KeyError(f"Field {f.name!r} not found in given data") from e
            try:
                if isinstance(v, list):
                    cast[f.name] = list(map(f.py_type, v))
                else:
                    cast[f.name] = f.py_type(v)
            except TypeError as e:
                raise TypeError(
                    f"Field {f.name!r} could not be cast to {f.py_type.__name__} from {type(v).__name__}"
                ) from e

        return cls(**cast)

    @classmethod
    def table_name_structured_compound(cls, other_name: str) -> str:
        return f"{cls.table_name}_{other_name}"

    def marshall_values_pod(self, parent_id: int | None = None) -> tuple[PodData, ...]:
        if parent_id is None:
            return tuple(getattr(self, f.name) for f in self.fields_pod)

        ls: list[t.Any] = [getattr(self, f.name) for f in self.fields_pod]
        ls.append(parent_id)
        return tuple(ls)

    def marshall_values_structured(
        self, row_id: int, field: Field
    ) -> cabc.Iterator[tuple[int, PodData]]:
        for v in getattr(self, field.name):
            yield (row_id, v)


def create_table(
    conn: sqlite3.Connection,
    data_class: type[DataClass],
    parent_cls_name: str | None = None,
) -> None:
    kinds: dict[Kind, list[Field]] = data_class.get_fields_by_kind()

    tab: str = " " * 4
    sql: str = f"CREATE TABLE IF NOT EXISTS {data_class.table_name} (\n"
    sql += f"{tab}row_id INTEGER PRIMARY KEY,\n"
    for f in kinds[Kind.POD]:
        sql += f"{tab}{f.name} {f.sql_type} NOT NULL,\n"
    if parent_cls_name is not None:
        sql += f"{tab}{parent_cls_name}_id INTEGER NOT NULL,\n"
    sql = sql.rstrip(",\n") + "\n"
    sql += ");\n"

    for f in kinds[Kind.DC]:
        other_data_class: type[DataClass] = f.py_type
        create_table(conn, other_data_class, parent_cls_name=data_class.table_name)

    for f in kinds[Kind.STRUCTURED]:
        sql += "\n"
        sql += f"CREATE TABLE IF NOT EXISTS {data_class.table_name_structured_compound(f.name)} (\n"
        sql += f"{tab}{data_class.table_name}_id INTEGER NOT NULL,\n"
        sql += f"{tab}{STRUCTURED_VALUE_COL} {f.sql_type} NOT NULL\n"
        sql += ");\n"

    for f in kinds[Kind.COMPOUND]:
        other_data_class: type[DataClass] = f.py_type
        create_table(conn, other_data_class)

        sql += "\n"
        sql += f"CREATE TABLE IF NOT EXISTS {data_class.table_name_structured_compound(other_data_class.table_name)} (\n"
        sql += f"{tab}{data_class.table_name}_id INTEGER NOT NULL,\n"
        sql += f"{tab}{other_data_class.table_name}_id INTEGER NOT NULL\n"
        sql += f");"

    conn.executescript(sql)
    conn.commit()


def _insert_record(
    cur: sqlite3.Cursor,
    record: DataClass,
    parent_table_name: str | None = None,
    parent_id: int | None = None,
) -> int:
    cur.execute(
        _sql_cmd_insert_pod_dc(record, parent_table_name=parent_table_name),
        record.marshall_values_pod(parent_id=parent_id),
    )
    row_id: int | None = cur.lastrowid
    if row_id is None:
        raise RuntimeError("Insertion was unsuccessful")

    for dc_field in record.fields_dc:
        dc_obj: DataClass = getattr(record, dc_field.name)
        _insert_record(
            cur, dc_obj, parent_table_name=record.table_name, parent_id=row_id
        )

    for struct_field in record.fields_structured:
        sql_cmd: str = _sql_cmd_insert_structured(record, struct_field)
        for values in record.marshall_values_structured(row_id, struct_field):
            cur.execute(sql_cmd, values)

    for comp_field in record.fields_compound:
        sql_cmd: str = _sql_cmd_insert_compound(record, comp_field)
        for item in getattr(record, comp_field.name):
            comp_row_id: int = _insert_record(cur, item)
            cur.execute(sql_cmd, (row_id, comp_row_id))

    return row_id


def _sql_cmd_insert_pod_dc(
    record: DataClass, parent_table_name: str | None = None
) -> str:
    if len(record.fields_pod) == 0 and parent_table_name is None:
        return f"INSERT INTO {record.table_name} DEFAULT VALUES"

    placeholders: str = ", ".join(
        "?" * (len(record.fields_pod) + int(parent_table_name is not None))
    )
    columns: str = ", ".join(f.name for f in record.fields_pod)
    if parent_table_name is not None:
        columns += f", {parent_table_name}_id"
    return f"INSERT INTO {record.table_name} ({columns}) VALUES ({placeholders})"


def _sql_cmd_insert_structured(record: DataClass, field: Field) -> str:
    cols: list[str] = [f"{record.table_name}_id", STRUCTURED_VALUE_COL]
    placeholders: str = ", ".join("?" * len(cols))
    return f"INSERT INTO {record.table_name_structured_compound(field.name)} ({", ".join(cols)}) VALUES ({placeholders})"


def _sql_cmd_insert_compound(record: DataClass, field: Field) -> str:
    other_data_class: type[DataClass] = field.py_type
    comp_table_name: str = other_data_class.table_name
    cols: list[str] = [f"{record.table_name}_id", f"{comp_table_name}_id"]
    placeholders: str = ", ".join("?" * len(cols))
    return f"INSERT INTO {record.table_name_structured_compound(comp_table_name)} ({", ".join(cols)}) VALUES ({placeholders})"


def insert_record(conn: sqlite3.Connection, record: DataClass) -> None:
    _insert_record(conn.cursor(), record)
    conn.commit()


def insert_records(conn: sqlite3.Connection, records: t.Sequence[DataClass]) -> None:
    # IMPROVEMENT: Consider using conn.executemany if this turns out to be
    # slow. Ref. the answer here:
    # https://stackoverflow.com/questions/29934154/sqlite-get-id-and-insert-when-using-executemany
    cur: sqlite3.Cursor = conn.cursor()
    for record in records:
        _insert_record(cur, record)
    conn.commit()


def select_all_records[T: DataClass](
    conn: sqlite3.Connection, data_cls: type[T], row_id: int | None = None
) -> list[T]:
    cur: sqlite3.Cursor = conn.cursor()
    sel_stmt: str = f"SELECT * FROM {data_cls.table_name}"
    if row_id is not None:
        sel_stmt += f" WHERE row_id = {row_id}"
    cur.execute(sel_stmt)
    records: list[list[PodData]] = [list(r) for r in cur.fetchall()]
    objects: list[T] = []
    for row in records:
        rec_id: int = t.cast(int, row.pop(0))
        obj_kwargs: dict[str, PodData | DataClass | StructuredData | CompoundData] = {
            f_p.name: f_p.py_type(v) for f_p, v in zip(data_cls.fields_pod, row)
        }
        obj_kwargs["row_id"] = rec_id
        for f_d in data_cls.fields_dc:
            dc_type: type[DataClass] = f_d.py_type
            cur.execute(
                f"SELECT * FROM {dc_type.table_name} WHERE {data_cls.table_name}_id = {rec_id}"
            )
            rows_dc: list[tuple] = cur.fetchall()
            if not len(rows_dc) == 1:
                raise RuntimeError(
                    f"Did not find exactly one row for {data_cls.table_name}_id={rec_id}"
                )
            obj_kwargs[f_d.name] = rows_dc[0][0]
        for f_s in data_cls.fields_structured:
            cur.execute(
                f"SELECT * FROM {data_cls.table_name_structured_compound(f_s.name)} WHERE {data_cls.table_name}_id = {rec_id}"
            )
            rows_struct: list[tuple] = cur.fetchall()
            obj_kwargs[f_s.name] = [r[1] for r in rows_struct]
        for f_c in data_cls.fields_compound:
            cur.execute(
                f"SELECT * FROM {data_cls.table_name_structured_compound(f_c.py_type.__name__)} WHERE {data_cls.table_name}_id = {rec_id}"
            )
            rows_comp: list[tuple] = cur.fetchall()
            items: list = []
            for _, comp_id in rows_comp:
                items.extend(select_all_records(conn, f_c.py_type, row_id=comp_id))
            obj_kwargs[f_c.name] = items
        objects.append(data_cls(**obj_kwargs))
    return objects


# SANDALS::GENERATED_CLASSES
