"""Generated by sandals."""

from collections.abc import Generator
from enum import Enum, auto
import sqlite3
import typing as t


class FieldKind(Enum):
    POD = 1
    COMPOUND = auto()


class Field:
    def __init__(self, name: str, sql_type: str, kind: FieldKind) -> None:
        self.name: str = name
        self.sql_type: str = sql_type
        self.kind: FieldKind = kind


class DataClass:
    table_name: str
    fields: list[Field]

    def __init__(self, row_id: int, **kwargs) -> None:
        raise NotImplementedError(f"Cannot initialize base class {type(self).__name__}")

    @classmethod
    def from_dict(cls, data: dict[str, t.Any]) -> "DataClass":
        return cls(0, **data)

    def marshall_values(self) -> tuple:
        return tuple(getattr(self, f.name) for f in self.fields)


def create_table(conn: sqlite3.Connection, data_class: type[DataClass]) -> None:
    kinds: dict[FieldKind, list[Field]] = _fields_by_kind(data_class)

    tab: str = " " * 4
    sql: str = f"CREATE TABLE IF NOT EXISTS {data_class.table_name} (\n"
    sql += f"{tab}row_id INTEGER PRIMARY KEY,\n"
    for f in kinds[FieldKind.POD]:
        sql += f"{tab}{f.name} {f.sql_type} NOT NULL,\n"
    sql = sql.rstrip(",\n") + "\n"
    sql += ");\n"

    if len(kinds[FieldKind.COMPOUND]) > 0:
        for f in kinds[FieldKind.COMPOUND]:
            sql += "\n"
            sql += f"CREATE TABLE IF NOT EXISTS {data_class.table_name}_{f.name} (\n"
            sql += f"{tab}{data_class.table_name}_id INTEGER NOT NULL,\n"
            sql += f"{tab}value {f.sql_type} NOT NULL,\n"
            sql += ");\n"

    conn.execute(sql)
    conn.commit()


def _fields_by_kind(data_class: type[DataClass]) -> dict[FieldKind, list[Field]]:
    kinds: dict[FieldKind, list[Field]] = {
        FieldKind.POD: [],
        FieldKind.COMPOUND: [],
    }
    for f in data_class.fields:
        if f.kind is FieldKind.POD:
            kinds[FieldKind.POD].append(f)
        elif f.kind is FieldKind.COMPOUND:
            kinds[FieldKind.COMPOUND].append(f)
    return kinds


def insert_record(conn: sqlite3.Connection, record: DataClass) -> None:
    placeholders: str = ", ".join("?" * len(record.fields))
    columns: str = ", ".join(f.name for f in record.fields)
    sql: str = f"INSERT INTO {record.table_name} ({columns}) VALUES ({placeholders})"
    conn.execute(sql, record.marshall_values())
    conn.commit()


def insert_records(conn: sqlite3.Connection, records: t.Sequence[DataClass]) -> None:
    if len(records) == 0:
        return
    placeholders: str = ", ".join("?" * len(records[0].fields))
    columns: str = ", ".join(f.name for f in records[0].fields)
    sql: str = (
        f"INSERT INTO {records[0].table_name} ({columns}) VALUES ({placeholders})"
    )
    conn.executemany(sql, _generate_records_iterable(records))
    conn.commit()


def _generate_records_iterable(
    records: t.Iterable[DataClass],
) -> Generator[tuple[str, ...]]:
    for rec in records:
        yield rec.marshall_values()


T = t.TypeVar("T", bound=DataClass)


def select_all_records[T](conn: sqlite3.Connection, data_cls: type[T]) -> list[T]:
    cur: sqlite3.Cursor = conn.execute(f"SELECT * FROM {data_cls.table_name}")
    data: list[tuple] = cur.fetchall()
    return [data_cls(*params) for params in data]


# SANDALS::GENERATED_CLASSES
