"""Generated by sandals."""

import collections.abc as cabc
from enum import Enum, auto
import sqlite3
import typing as t


COMPOUND_VALUE_COL: t.Final[str] = "value"


type PodData = int | float | str
type PodType = type[int | float | str]


class PodSqlite(t.NamedTuple):
    type_: PodType
    sql: str


SQLITE_POD_TYPE_MAP: t.Final[dict[str, PodSqlite]] = {
    "int": PodSqlite(type_=int, sql="INTEGER"),
    "float": PodSqlite(type_=float, sql="REAL"),
    "str": PodSqlite(type_=str, sql="TEXT"),
}


class Kind(Enum):
    POD = 1
    COMPOUND = auto()


class Field:
    def __init__(self, name: str, sql_type: str, kind: Kind) -> None:
        self.name: str = name
        self.sql_type: str = sql_type
        self.kind: Kind = kind


class DataClass:
    """Holds data going to and coming from SQLite databases."""

    table_name: str
    fields: list[Field]

    def __init__(self, **kwargs) -> None:
        self.fields_by_kind: dict[Kind, list[Field]] = self.get_fields_by_kind()

    @classmethod
    def get_fields_by_kind(cls) -> dict[Kind, list[Field]]:
        fbk: dict[Kind, list[Field]] = {Kind.POD: [], Kind.COMPOUND: []}
        for f in cls.fields:
            fbk[f.kind].append(f)
        return fbk

    @classmethod
    def get_fields_pod(cls) -> list[Field]:
        return cls.get_fields_by_kind()[Kind.POD]

    @classmethod
    def get_fields_compound(cls) -> list[Field]:
        return cls.get_fields_by_kind()[Kind.COMPOUND]

    @property
    def fields_pod(self) -> list[Field]:
        return self.fields_by_kind[Kind.POD]

    @property
    def fields_compound(self) -> list[Field]:
        return self.fields_by_kind[Kind.COMPOUND]

    @classmethod
    def from_dict(cls, data: dict[str, t.Any]) -> "DataClass":
        return cls(**data)

    @classmethod
    def table_name_compound(cls, field_name: str) -> str:
        return f"{cls.table_name}_{field_name}"

    def marshall_values_pod(self) -> tuple[PodData, ...]:
        return tuple(getattr(self, f.name) for f in self.fields_pod)

    def marshall_values_compound(
        self, row_id: int, field: Field
    ) -> cabc.Iterator[tuple[int, PodData]]:
        for v in getattr(self, field.name):
            yield (row_id, v)


def create_table(conn: sqlite3.Connection, data_class: type[DataClass]) -> None:
    kinds: dict[Kind, list[Field]] = data_class.get_fields_by_kind()

    tab: str = " " * 4
    sql: str = f"CREATE TABLE IF NOT EXISTS {data_class.table_name} (\n"
    sql += f"{tab}row_id INTEGER PRIMARY KEY,\n"
    for f in kinds[Kind.POD]:
        sql += f"{tab}{f.name} {f.sql_type} NOT NULL,\n"
    sql = sql.rstrip(",\n") + "\n"
    sql += ");\n"

    if len(kinds[Kind.COMPOUND]) > 0:
        for f in kinds[Kind.COMPOUND]:
            sql += "\n"
            sql += f"CREATE TABLE IF NOT EXISTS {data_class.table_name_compound(f.name)} (\n"
            sql += f"{tab}{data_class.table_name}_id INTEGER NOT NULL,\n"
            sql += f"{tab}{COMPOUND_VALUE_COL} {f.sql_type} NOT NULL\n"
            sql += ");\n"

    conn.executescript(sql)
    conn.commit()


def _insert_record(conn: sqlite3.Connection, record: DataClass) -> None:
    cur: sqlite3.Cursor = conn.cursor()
    cur.execute(_sql_cmd_insert_pod(record), record.marshall_values_pod())
    row_id: int | None = cur.lastrowid
    if row_id is None:
        raise RuntimeError("Insertion was unsuccessful")

    for comp_field in record.fields_compound:
        sql_cmd: str = _sql_cmd_insert_compound(record, comp_field)
        for values in record.marshall_values_compound(row_id, comp_field):
            cur.execute(sql_cmd, values)


def _sql_cmd_insert_pod(record: DataClass) -> str:
    placeholders: str = ", ".join("?" * len(record.fields_pod))
    columns: str = ", ".join(f.name for f in record.fields_pod)
    return f"INSERT INTO {record.table_name} ({columns}) VALUES ({placeholders})"


def _sql_cmd_insert_compound(record: DataClass, field: Field) -> str:
    cols: list[str] = [f"{record.table_name}_id", COMPOUND_VALUE_COL]
    placeholders: str = ", ".join("?" * len(cols))
    return f"INSERT INTO {record.table_name_compound(field.name)} ({", ".join(cols)}) VALUES ({placeholders})"


def insert_record(conn: sqlite3.Connection, record: DataClass) -> None:
    _insert_record(conn, record)
    conn.commit()


def insert_records(conn: sqlite3.Connection, records: t.Sequence[DataClass]) -> None:
    # IMPROVEMENT: Consider using conn.executemany if this turns out to be
    # slow. Ref. the answer here:
    # https://stackoverflow.com/questions/29934154/sqlite-get-id-and-insert-when-using-executemany
    for record in records:
        _insert_record(conn, record)
    conn.commit()


def select_all_records[T: DataClass](
    conn: sqlite3.Connection, data_cls: type[T]
) -> list[T]:
    cur: sqlite3.Cursor = conn.cursor()
    cur.execute(f"SELECT * FROM {data_cls.table_name}")
    records: list[list[PodData | list[PodData]]] = [list(r) for r in cur.fetchall()]
    for row in records:
        row_id: int = t.cast(int, row[0])
        data_comp_fields: list[list[PodData]] = []
        for f_cpd in data_cls.get_fields_compound():
            cur.execute(
                f"SELECT * FROM {data_cls.table_name_compound(f_cpd.name)} WHERE {data_cls.table_name}_id = {row_id}"
            )
            rows_cpd: list[tuple] = cur.fetchall()
            data_comp_fields.append([r[1] for r in rows_cpd])
        row.extend(data_comp_fields)
    return [data_cls(*params) for params in records]


# SANDALS::GENERATED_CLASSES
