"""Logic for generating the Python classes template."""

from sandals import config


def generate_python_template() -> None:
    """Generate the Python classes template."""
    with open(
        config.TEMPLATE_PATH.with_stem(config.TEMPLATE_PATH.stem + ".gen"), "w"
    ) as f:
        f.write(
            f"""\"\"\"Generated by sandals.\"\"\"

import sqlite3


class DataClass:
    table_name: str
    _fields: list[str]

    def marshall_values(self) -> tuple:
        return tuple(getattr(self, field) for field in self._fields)


# {config.TEMPLATE_LOC_GENERATED_CLASSES}


def insert_record(conn: sqlite3.Connection, record: Record) -> None:
    placeholders: str = ", ".join("?" * len(record._fields))
    columns: str = ", ".join(record._fields)
    sql: str = f"INSERT INTO {{record.table_name}} ({{columns}}) VALUES ({{placeholders}})"
    conn.execute(sql, record.marshall_values())
    conn.commit()
"""
        )
    print(f"Generated template at {config.TEMPLATE_PATH}")
    print("Remember to rename the generated file.")


if __name__ == "__main__":
    generate_python_template()
